# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmsd_betw_matrices <- function(x, y) {
    .Call(`_lineup2_rmsd_betw_matrices`, x, y)
}

mad_betw_matrices <- function(x, y) {
    .Call(`_lineup2_mad_betw_matrices`, x, y)
}

fscale <- function(x) {
    .Call(`_lineup2_fscale`, x)
}

fscalev <- function(x) {
    .Call(`_lineup2_fscalev`, x)
}

